### ISSUE TITLE
with platform io error

### ISSUE THREAD

**Issue by Isabellaew** [AgainPsychoX/AgainPsychoX#1]
hello bro, very good program, I tried compiling with PlatformIO but it got an error, please help how to solve this problem, I'm really new to this.
![erer](https://github.com/AgainPsychoX/AgainPsychoX/assets/134220854/ab5e0cc6-8cbd-428f-bf9e-7f07b4ecb137)

Thank You

**Comment by AgainPsychoX** [comment]
Hello, sorry for very late response, I didn't notice in all the emails...

As for the issue, which seems to be related to my [AquariumController](https://github.com/AgainPsychoX/AquariumController) project. The `webEncoded` folder contents are generated from files from `web` folder. You need to run the `_prepareWeb.bat` script first time, and  after every modification to any file inside `web` folder.

What does it do? It runs a script I wrote that converts the files in `web` into GZIPed (compressed) versions, ready to be embedded/compiled into the binary. It both saves program space (which allows for more files and more code) and bandwidth (it's faster to send pre-compressed data to the web-browser). Aside from that, the script prepares the special macro `WEB_REGISTER_ALL_STATIC` which registers all the static web files request handlers for the web-server, along with some required caching/content-type headers and other stuff.

Let me know if you need any more help, I am recently more actively reading emails (I hope 😅)
